### ISSUE TITLE
This integration does not work

### ISSUE THREAD

**Issue by djairjr** [Seeed-Solution/SenseCraft-HomeAssistant#4]
In step 11 of the wiki - [Connecting to Home Assistant | Seeed Studio Wiki 2](https://wiki.seeedstudio.com/connect_vision_ai_v2_to_ha/#integrate-grove-vision-ai-v2-into-home-assistant), I can’t get Groove Vision AI V2 to be found by Homeassistant. Looking at the EMQX Logs, I notice that the board connects with MQTT. But in step by step, I can’t make the connection. Timeout error occurs.

The system does not automatically find my device, and manual configuration is required. In this case, when filling out the SETUP MQTT SERVER form with my server information, I cannot connect through setup.

MQTT connection timeout

EMQX - Connection Info

|Status|Connected|
|Node|emqx@myHomeAssistantServer.local|
|Client ID| grove_vision_ai_v2
|Username| myuser
|Protocol| MQTT v3.1.1|
|IP Address| myGrooveIpAddress:57773|
|Keepalive| 15|
|Clean Session|true|
|Bridge|false|
|Connected At|2024-05-11 13:22:39|

Session Info

|Session Expiry Interval|0|
|Created At|2024-05-11 13:22:39|
|Heap Size|2586 bytes|
|Subscriptions|1/infinity|
|Message Queue|0/1000View Message|
|Inflight|0/32View Message|
|QoS 2 Message Receive Queue|0/100|

Used the mqtt2uart example and get wifi and mqtt connected. EQMX detects the board, but the integration does not.
Also when SenseCraft extension try to integrate my Groove Vision AI V2, the name header start with grove_vision_ai_we2_uniqueid and not grove_vision_ai_v2_uniqueid.

**Comment by chenwenhao568** [comment]
Already solved，firmware has updated the mqtt id to grove_vision_ai_v2

**Comment by chenwenhao568** [comment]
v1.1.3 has fixed this bug
